### PR TITLE
options for multiple services

### PR DESCRIPTION
**Pull request by FranckErnewein**
Tweetping connect should allow to receive different notification for each service in realtime
for example, for the wall we want to receive each new item.
for the activity we want to be notify only that a new item appends (but we do not car about the content).
etc.

I suggest to replace le last parameter `<string> serverUrl` by a javascript plain object which contains différent options. some of them with default values.

For now I identify server and services list.

### CODE REVIEW

**Comment by rehia** [comment]
I was thinking about how you would use this connector...
In the `onEvent` callback, you will have to make some test on the service which provided the item.
You have already thought about having one call to `connect` for each service you want to connect to.
I would be curious why you let that option away.
I find that option good because:
- You provide a dedicated onEvent for each kind of widget/service
- You know how many web sockets you open, and you open them when you want (I imagine that `connect`actually opens as many web sockets as services)

I don't have the best overview on the usage of it, but that's my 2 cents contribution

**Comment by rehia** [comment]
I would also suggest to avoid stream ids as numbers, and suggest to use strings, as long as numbers are quite useless here, and strings better support further evolutions.

**Comment by FranckErnewein** [comment]
stream ID as a string => ok
for multiple services you suggest: 

``` js
connect("1234", "wall", message =>  console.log('new wall message:', message));
connect("1234", "activity", event =>  console.log('new activity event:', event));
```

makes sense

**Comment by FranckErnewein** [comment]
concerning the implementation (how many websockets are open, what kind of protocols are used etc.) this is not very important yet.
I focus on the public API we will provide to our users.

**Comment by FranckErnewein** [comment]
hum ... so how do you "unsubscribe" to a service ?

**Comment by rehia** [comment]
For `connect` example on multiple services: yes, that's what I meant. I find this option a good one, but not sure if it's the best. 

Best option to unsubscribe seems to be by getting an object (with a function) or directly a function out of `connect` call, and call it whenever you need.
Easier to implement as well (because the closure you return keeps a

**Comment by FranckErnewein** [comment]
`connect(streamId, serviceName, callback)` could return a stream ?

``` js
const stream = connect("1234", "wall");
stream.on('data', (message) => console.log(message));
// or ...
stream.pipe(parser).pipe(displayer).pipe(whatever);
// end to close it
stream.end();
```

**Pull request merged**
